parameters:
    - name: bot.image
      type: string
    - name: bot.imageName
      type: string
    - name: bot.sshEndpoint
      type: string
    - name: bot.dockerRegistryEndpoint
      type: string
    - name: bot.envFile
      type: string

jobs:
    - job: ValidateParameters
      displayName: Validate parameters
      steps:
          - template: RequiredValue.yml
            parameters:
                name: 'bot.image'
                value: parameters.bot.image
          - template: RequiredValue.yml
            parameters:
                name: 'bot.imageName'
                value: parameters.bot.imageName
          - template: RequiredValue.yml
            parameters:
                name: 'bot.sshEndpoint'
                value: parameters.bot.sshEndpoint
          - template: RequiredValue.yml
            parameters:
                name: 'bot.dockerRegistryEndpoint'
                value: parameters.bot.dockerRegistryEndpoint
          - template: RequiredValue.yml
            parameters:
                name: 'bot.envFile'
                value: parameters.bot.envFile
